# Generated by Django 3.2.7 on 2021-09-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vechile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vechile_Mileage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day_mileage', models.IntegerField()),
                ('date', models.DateField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vechile.vechile')),
            ],
        ),
    ]
