# Generated by Django 3.2.7 on 2021-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechile', '0002_vechile_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile_mileage',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
