# Generated by Django 3.2.7 on 2021-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechile', '0003_alter_vechile_mileage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile_mileage',
            name='day_mileage',
            field=models.IntegerField(null=True),
        ),
    ]
