# Generated by Django 3.2.7 on 2021-09-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechile', '0004_alter_vechile_mileage_day_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile_mileage',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
