# Generated by Django 3.2.7 on 2021-09-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vechile', '0005_alter_vechile_mileage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile_mileage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vechile.vechile'),
        ),
    ]
